version: 2

models:
  - name: stg_ash__categories
    columns:
      - name: id
        data_type: varchar
        data_tests:
          - not_null
          - unique
      - name: name
        data_type: varchar
        data_tests:
          - not_null
          - unique
      - name: description
        data_type: varchar
      - name: is_available_in_app
        data_type: boolean
        data_tests:
          - not_null
  - name: stg_ash__groups
    columns:
      - name: id
        data_type: varchar
        data_tests:
          - not_null
          - unique
      - name: name
        data_type: varchar
        data_tests:
          - not_null
          - unique
  - name: stg_ash__inventory
    columns:
      - name: product_id
        data_type: varchar
        data_tests:
          - not_null
      - name: store_id
        data_type: varchar
        data_tests:
          - not_null
      - name: inventory_date
        data_type: date
        data_tests:
          - not_null
      - name: on_floor_days_count
        data_type: integer
        data_tests:
          - not_null
      - name: floor_start_date
        data_type: date
        data_tests:
          - not_null
      - name: quantity
        data_type: integer
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - product_id
            - store_id
            - inventory_date
  - name: stg_ash__products
    columns:
      - name: id
        data_type: varchar
        data_tests:
          - not_null
      - name: category_id
        data_type: varchar
        data_tests:
          - not_null
      - name: subcategory_id
        data_type: varchar
        data_tests:
          - not_null
      - name: group_id
        data_type: varchar
        data_tests:
          - not_null
      - name: subgroup_id
        data_type: varchar
        data_tests:
          - not_null
      - name: status
        data_type: varchar
        data_tests:
          - not_null
      - name: purchase_status
        data_type: varchar
      - name: is_exclusive
        data_type: boolean
        data_tests:
          - not_null
      - name: is_commodity
        data_type: boolean
        data_tests:
          - not_null
      - name: is_new
        data_type: boolean
        data_tests:
          - not_null
      - name: is_available_in_app
        data_type: boolean
        data_tests:
          - not_null
      - name: name
        data_type: varchar
        data_tests:
          - not_null
      - name: type
        data_type: varchar
        data_tests:
          - not_null
      - name: code
        data_type: varchar
      - name: color
        data_type: varchar
      - name: image_url
        data_type: varchar
  - name: stg_ash__recommendations
    columns:
      - name: store_id
        data_type: varchar
        data_tests:
          - not_null
      - name: product_id
        data_type: varchar
        data_tests:
          - not_null
      - name: is_on_floor
        data_type: boolean
        data_tests:
          - not_null
      - name: past_sales
        data_type: number(38,2)
        data_tests:
          - not_null
      - name: avg_daily_on_floor_sales
        data_type: number(38,2)
        data_tests:
          - not_null
      - name: is_available_in_app
        data_type: boolean
        data_tests:
          - not_null
      - name: flags
        data_type: array
        data_tests:
          - not_null
      - name: predicted_sales
        data_type: number(38,2)
      - name: floor_date
        data_type: date
  - name: stg_ash__stores
    columns:
      - name: id
        data_type: varchar
        data_tests:
          - not_null
          - unique
      - name: name
        data_type: varchar
        data_tests:
          - not_null
          - unique
      - name: type
        data_type: varchar
        data_tests:
          - not_null
      - name: is_active
        data_type: boolean
        data_tests:
          - not_null
      - name: address_city
        data_type: varchar
      - name: address_country
        data_type: varchar
      - name: address_postal_code
        data_type: varchar
      - name: address_state
        data_type: varchar
      - name: floor_sqft
        data_type: integer
  - name: stg_ash__store_daily_visitors
    columns:
      - name: store_id
        data_type: varchar
        data_tests:
          - not_null
      - name: created_date
        data_type: date
        data_tests:
          - not_null
      - name: visitor_count
        data_type: number(38,2)
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - store_id
            - created_date
  - name: stg_ash__store_monthly_sales
    columns:
      - name: store_id
        data_type: varchar
        data_tests:
          - not_null
      - name: year
        data_type: integer
        data_tests:
          - not_null
      - name: month
        data_type: integer
        data_tests:
          - not_null
      - name: amount_per_visitor
        data_type: number(38,2)
      - name: amount_per_visitor_per_sqft
        data_type: number(38,2)
      - name: total_amount
        data_type: number(38,2)
        data_tests:
          - not_null
      - name: total_visitor_count
        data_type: integer
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - store_id
            - year
            - month
  - name: stg_ash__subcategories
    columns:
      - name: id
        data_type: varchar
        data_tests:
          - not_null
          - unique
      - name: name
        data_type: varchar
        data_tests:
          - not_null
      - name: category_id
        data_type: varchar
        data_tests:
          - not_null
  - name: stg_ash__subgroups
    columns:
      - name: id
        data_type: varchar
        data_tests:
          - not_null
          - unique
      - name: name
        data_type: varchar
        data_tests:
          - not_null
          - unique
  - name: stg_ash__transactions
    columns:
      - name: order_id
        data_type: varchar
        data_tests:
          - not_null
      - name: product_id
        data_type: varchar
        data_tests:
          - not_null
      - name: store_id
        data_type: varchar
        data_tests:
          - not_null
      - name: transaction_date
        data_type: date
        data_tests:
          - not_null
      - name: is_in_inventory
        data_type: boolean
        data_tests:
          - not_null
      - name: is_on_floor
        data_type: boolean
        data_tests:
          - not_null
      - name: on_floor_days_count
        data_type: integer
        data_tests:
          - not_null
      - name: amount
        data_type: number(38,2)
        data_tests:
          - not_null
      - name: category_id
        data_type: varchar
      - name: subcategory_id
        data_type: varchar
      - name: group_id
        data_type: varchar
      - name: quantity
        data_type: integer
        data_tests:
          - not_null
  - name: stg_ash__sisters
    columns:
      - name: product_id
        data_type: varchar
        data_tests:
          - not_null
      - name: id
        data_type: varchar
      - name: status
        data_type: varchar
      - name: group_id
        data_type: varchar
        data_tests:
          - not_null
      - name: subgroup_id
        data_type: varchar
        data_tests:
          - not_null
      - name: category_id
        data_type: varchar
        data_tests:
          - not_null
