create or replace table arteli_db_ingestion.tdg_ingestion.raw_old_transactions (
    _file varchar(256) not null,
    _line number(38,0) not null,
    _modified timestamp_tz(9),
    location_id varchar(256),
    order_id varchar(256),
    written_date date,
    category_id varchar(256),
    group_id varchar(256),
    series_id varchar(256),
    vendor_style varchar(256),
    product_id varchar(256),
    product_name varchar(256),
    reason_code varchar(256),
    drop_down_used varchar(256),
    qty integer,
    other_discount varchar(256),
    retail_price float,
    promo_price float,
    sell_price float,
    sell_vs_retail_disc float,
    sell_vs_promo_disc float,
    promo_price_degredation varchar(256),
    gm_impact_by_disc float,
    gm_sell_price float,
    gm_retail_price float,
    salesperson_name varchar(256),
    price_override_staff_id varchar(256),
    override_staff_name varchar(256),
    price_exception_comment varchar(),
    kit_product_id varchar(256),
    vendor_model_number varchar(256),
    primary key (_file, _line)
);
